/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.renep.kata.hangman;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HangmanTest {

	Hangman hangman;
	InputOutputFake io;

	@BeforeEach
	void setup() {
		io = new InputOutputFake();
		hangman = new Hangman(io);
	}

	@Test
	void print_round_0_with_default_guessWord() {
		// when
		hangman.run();

		// then
		String line = io.getNextLine();
		assertEquals("Runde 0. Bisher geraten: _______. Was wählst du für ein Zeichen?", line);
	}


	@Test
	void print_round_0_with_guessWord_that_has_5_characters() {
		// given
		hangman.setWordToGuess("12345");

		// when
		hangman.run();

		// then
		String line = io.getNextLine();
		assertEquals("Runde 0. Bisher geraten: _____. Was wählst du für ein Zeichen?", line);
	}


	@Test
	void print_round_0_with_guessWord_that_has_6_characters() {
		// given
		hangman.setWordToGuess("123456");

		// when
		hangman.run();

		// then
		String line = io.getNextLine();
		assertEquals("Runde 0. Bisher geraten: ______. Was wählst du für ein Zeichen?", line);
	}

	@Test
	void generated_guessWord_has_10_character() {
		// given
		hangman.setWordToGuess("1234567890");

		// when
		assertEquals("__________", hangman.generateGuessedWord());
	}

	@Test
	void generated_guessWord_has_20_character() {
		// given
		hangman.setWordToGuess("12345678901234567890");

		// when
		assertEquals("____________________", hangman.generateGuessedWord());
	}

	@Test
	void wordToGuess_should_not_be_null() {
		assertEquals("_______", hangman.generateGuessedWord());
//		assertNotNull(hangman.wordToGuess);
	}

	@Test
	void wordToGuess_should_not_be_null_2() {
		hangman.setWordToGuess(null);

		// then
		assertEquals("_______", hangman.generateGuessedWord());
	}

	@Test
	void wordToGuess_should_not_be_null_3() {
		hangman.setWordToGuess("12345678901234567890");
		hangman.setWordToGuess(null);

		// then
		assertEquals("____________________", hangman.generateGuessedWord());
	}

	@Test
	void generatedWord_has_same_length_as_wordToGuess () {
		String wordToGuess = "aaaaa";
		String expectedResult = "_____";
		for (int i=0; i<5; i++) {
			wordToGuess += "a";
			expectedResult += "_";

			// when
			hangman.setWordToGuess(wordToGuess);

			// then
			assertEquals(expectedResult, hangman.generateGuessedWord());
		}

	}
}
