/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.renep.kata.hangman;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HangmanTest {
	@Test
	void appHasAGreeting() {
		Hangman classUnderTest = new Hangman();

		assertNotNull(classUnderTest.getGreeting());
	}
}
