/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.renep.kata.hangman;



public class Hangman {
	private final InputOutput io;


	private String wordToGuess = "hangman";

	public Hangman(InputOutput io) {
		this.io = io;
	}

	public static void main(String[] args) {
		new Hangman(new SystemInputOutput()).run();
	}

	public void run() {
		String guessedWord = generateGuessedWord();

		io.println("Runde 0. Bisher geraten: " + guessedWord + ". Was wählst du für ein Zeichen?");
	}

	String generateGuessedWord() {
		String guessedWord = "";
		for(int index=0; index != wordToGuess.length(); index++) {
			guessedWord = guessedWord + "_";
		}
		return guessedWord;
	}

	public void setWordToGuess(String wordToGuess) {
		if (wordToGuess != null) {
			this.wordToGuess = wordToGuess;
		}
	}
}
