/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.github.renep.kata.hangman;



public class Hangman {
	private final InputOutput io;
	public String wordToGuess;

	public Hangman(InputOutput io) {
		this.io = io;
	}

	public static void main(String[] args) {
		new Hangman(new SystemInputOutput()).run();
	}

	public void run() {
		String guessedWord = generateGuessedWord();

		io.println("Runde 0. Bisher geraten: " + guessedWord + ". Was wählst du für ein Zeichen?");
	}

	String generateGuessedWord() {
		String guessedWord = "_____";
		if (wordToGuess != null) {
			if (wordToGuess.length() == 10) {
				guessedWord = "__________";
			} else if (wordToGuess.length() == 20) {
				guessedWord = "____________________";
			} else if (wordToGuess.length() != 5) {
				guessedWord = "______";
			}
		} else {
			guessedWord = "_______";
		}
		return guessedWord;
	}
}
